# Generated by Django 3.1.2 on 2020-11-12 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='staff',
            options={'get_latest_by': 'created_at'},
        ),
        migrations.AddField(
            model_name='leave',
            name='purpose',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='leave',
            name='status',
            field=models.CharField(blank=True, choices=[('Rejected', 'Rejected'), ('Pending', 'Pending'), ('Approved', 'Approved')], max_length=100, null=True),
        ),
    ]
