# Generated by Django 3.1.2 on 2020-11-12 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_auto_20201112_1213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave',
            name='status',
            field=models.CharField(blank=True, choices=[('Rejected', 'Rejected'), ('Approved', 'Approved'), ('Pending', 'Pending')], max_length=100, null=True),
        ),
    ]
