# Generated by Django 3.1.2 on 2020-11-07 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('CH', 'Cashier'), ('HM', 'Hospital Manager'), ('IT', 'IT'), ('DR', 'Doctor'), ('HR', 'Human Resource'), ('NRS', 'Nurse'), ('PHM', 'Pharmacist'), ('Acc', 'Accountant')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(blank=True, choices=[('MU', 'Manager'), ('AD', 'Administrator'), ('SU', 'Support'), ('NU', 'Normal Staff')], max_length=255, null=True),
        ),
    ]
