# Generated by Django 3.1.2 on 2020-11-10 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20201107_2119'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='status',
            field=models.CharField(blank=True, choices=[('Active', 'Active'), ('Dismissed', 'Dismissed'), ('Suspended', 'Suspended'), ('Leave', 'Leave')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('Acc', 'Accountant'), ('CH', 'Cashier'), ('HM', 'Hospital Manager'), ('DR', 'Doctor'), ('IT', 'IT'), ('NRS', 'Nurse'), ('HR', 'Human Resource'), ('PHM', 'Pharmacist')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(blank=True, choices=[('SU', 'Support'), ('MU', 'Manager'), ('NU', 'Normal Staff'), ('AD', 'Administrator')], max_length=255, null=True),
        ),
    ]
