# Generated by Django 3.1.2 on 2020-11-03 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='defaultbills',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AddField(
            model_name='bill',
            name='status',
            field=models.IntegerField(blank=True, choices=[(1, 'Paid'), (0, 'Not Paid')], null=True),
        ),
        migrations.AlterField(
            model_name='bill',
            name='bill_type',
            field=models.CharField(blank=True, choices=[('PB', 'Procedure Bills'), ('CB', 'Card Bills'), ('PhB', 'Pharmacy Bills'), ('LB', 'Lab Bills'), ('WB', 'Ward Bills')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='defaultbills',
            name='bill_type',
            field=models.CharField(blank=True, choices=[('PB', 'Procedure Bills'), ('CB', 'Card Bills'), ('PhB', 'Pharmacy Bills'), ('LB', 'Lab Bills'), ('WB', 'Ward Bills')], max_length=100, null=True),
        ),
    ]
