# Generated by Django 3.1.2 on 2020-11-12 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_auto_20201107_2119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='bill_type',
            field=models.CharField(blank=True, choices=[('LB', 'Lab Bills'), ('PhB', 'Pharmacy Bills'), ('WB', 'Ward Bills'), ('CnB', 'Consultation Bill'), ('PB', 'Procedure Bills'), ('CB', 'Card Bills')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='defaultbills',
            name='bill_type',
            field=models.CharField(blank=True, choices=[('LB', 'Lab Bills'), ('PhB', 'Pharmacy Bills'), ('WB', 'Ward Bills'), ('CnB', 'Consultation Bill'), ('PB', 'Procedure Bills'), ('CB', 'Card Bills')], max_length=100, null=True),
        ),
    ]
