# Generated by Django 3.1.2 on 2020-11-12 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0010_auto_20201112_1455'),
        ('portal', '0004_auto_20201112_1235'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='prescription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bill_prescription', to='pharmacy.prescription'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='bill_type',
            field=models.CharField(blank=True, choices=[('PhB', 'Pharmacy Bills'), ('LB', 'Lab Bills'), ('PB', 'Procedure Bills'), ('CB', 'Card Bills'), ('WB', 'Ward Bills'), ('CnB', 'Consultation Bill')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='bill',
            name='status',
            field=models.IntegerField(blank=True, choices=[(1, 'Paid'), (0, 'Not Paid')], null=True),
        ),
        migrations.AlterField(
            model_name='defaultbills',
            name='bill_type',
            field=models.CharField(blank=True, choices=[('PhB', 'Pharmacy Bills'), ('LB', 'Lab Bills'), ('PB', 'Procedure Bills'), ('CB', 'Card Bills'), ('WB', 'Ward Bills'), ('CnB', 'Consultation Bill')], max_length=100, null=True),
        ),
    ]
