# Generated by Django 3.1.2 on 2020-10-20 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_auto_20201020_1315'),
    ]

    operations = [
        migrations.AddField(
            model_name='bed',
            name='allocate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bed_allocate', to='management.bedallocate'),
        ),
        migrations.AddField(
            model_name='bed',
            name='bed_allocates',
            field=models.ManyToManyField(blank=True, related_name='bed_bed_allocate', to='management.BedAllocate'),
        ),
        migrations.AddField(
            model_name='bed',
            name='status',
            field=models.CharField(blank=True, choices=[('Assigned', 'Assigned'), ('Unassigned', 'Unassigned')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='marital_status',
            field=models.CharField(blank=True, choices=[('Widowed', 'Widowed'), ('Single', 'Single'), ('Divorced', 'Divoreced'), ('Married', 'Married')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='treatment',
            name='status',
            field=models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Canceled', 'Canceled'), ('Completed', 'Completed')], max_length=100, null=True),
        ),
    ]
