# Generated by Django 3.1.2 on 2020-10-27 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0009_auto_20201027_1246'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bedallocate',
            old_name='admitted_at',
            new_name='date_admitted',
        ),
        migrations.RemoveField(
            model_name='bedallocate',
            name='discharged_at',
        ),
        migrations.AddField(
            model_name='bedallocate',
            name='time_admitted',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bedallocate',
            name='time_discharged',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='marital_status',
            field=models.CharField(blank=True, choices=[('Married', 'Married'), ('Divorced', 'Divoreced'), ('Single', 'Single'), ('Widowed', 'Widowed')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='patient_type',
            field=models.CharField(blank=True, choices=[('OPD', 'OPD'), ('ER', 'EMERGENCY'), ('WARD', 'WARD')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='treatment',
            name='status',
            field=models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Canceled', 'Canceled'), ('Completed', 'Completed')], max_length=100, null=True),
        ),
    ]
