# Generated by Django 3.1.2 on 2020-10-27 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0010_auto_20201027_1250'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bed',
            options={'ordering': ('number',)},
        ),
        migrations.AddField(
            model_name='bedallocate',
            name='date_discharged',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='gender',
            field=models.CharField(blank=True, choices=[('Female', 'Female'), ('Male', 'Male')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='marital_status',
            field=models.CharField(blank=True, choices=[('Married', 'Married'), ('Widowed', 'Widowed'), ('Divorced', 'Divoreced'), ('Single', 'Single')], max_length=100, null=True),
        ),
        migrations.AlterModelTable(
            name='bed',
            table='bed',
        ),
    ]
