# Generated by Django 3.1.2 on 2020-11-09 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0002_auto_20201109_1229'),
        ('management', '0020_auto_20201109_1224'),
    ]

    operations = [
        migrations.AddField(
            model_name='treatment',
            name='pharmacy_prescription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='treatment_prescription', to='pharmacy.prescription'),
        ),
        migrations.AlterField(
            model_name='complaints',
            name='status',
            field=models.CharField(blank=True, choices=[('Resolved', 'Resolved'), ('Pending', 'Pending'), ('Canceled', 'Canceled')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='marital_status',
            field=models.CharField(blank=True, choices=[('Married', 'Married'), ('Divorced', 'Divoreced'), ('Widowed', 'Widowed'), ('Single', 'Single')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='patient_type',
            field=models.CharField(blank=True, choices=[('ER', 'EMERGENCY'), ('Ward', 'Ward'), ('OPD', 'OPD'), ('DISCHARGED', 'DISCHARGED')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='treatment',
            name='status',
            field=models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Completed', 'Completed'), ('Canceled', 'Canceled')], max_length=100, null=True),
        ),
    ]
