# Generated by Django 3.1.2 on 2020-11-10 11:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('management', '0025_auto_20201109_1616'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expenditure',
            old_name='cost',
            new_name='total_cost',
        ),
        migrations.AlterField(
            model_name='complaints',
            name='status',
            field=models.CharField(blank=True, choices=[('Resolved', 'Resolved'), ('Pending', 'Pending'), ('Canceled', 'Canceled')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='expenditure',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenditures', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='patient',
            name='marital_status',
            field=models.CharField(blank=True, choices=[('Single', 'Single'), ('Widowed', 'Widowed'), ('Divorced', 'Divoreced'), ('Married', 'Married')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='patient_type',
            field=models.CharField(blank=True, choices=[('ER', 'EMERGENCY'), ('Ward', 'Ward'), ('OPD', 'OPD'), ('DISCHARGED', 'DISCHARGED')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='request',
            name='department',
            field=models.CharField(blank=True, choices=[('Management', 'Management'), ('Pharmacy', 'Pharmacy'), ('Ward', 'Ward'), ('Account', 'Account'), ('HR', 'Human Resource')], max_length=200, null=True),
        ),
        migrations.CreateModel(
            name='LeavePeriod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(default=django.utils.timezone.now)),
                ('end_date', models.DateField(default=django.utils.timezone.now)),
                ('num_of_days', models.IntegerField(default=0)),
                ('days_allowed', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leave_periods', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'leave_period',
            },
        ),
    ]
