# Generated by Django 3.1.2 on 2020-11-23 11:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('management', '0033_auto_20201117_1415'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='patient',
        #     name='bp',
        # ),
        # migrations.RemoveField(
        #     model_name='patient',
        #     name='respiration',
        # ),
        # migrations.RemoveField(
        #     model_name='patient',
        #     name='temperature',
        # ),
        # migrations.RemoveField(
        #     model_name='patient',
        #     name='weight',
        # ),
        migrations.AlterField(
            model_name='patient',
            name='marital_status',
            field=models.CharField(blank=True, choices=[('Single', 'Single'), ('Divorced', 'Divorced'), ('Married', 'Married'), ('Widowed', 'Widowed')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='patient_type',
            field=models.CharField(blank=True, choices=[('Ward', 'Ward'), ('ER', 'EMERGENCY'), ('OPD', 'OPD'), ('DISCHARGED', 'DISCHARGED')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='request',
            name='department',
            field=models.CharField(blank=True, choices=[('Ward', 'Ward'), ('Management', 'Management'), ('Pharmacy', 'Pharmacy'), ('Account', 'Account'), ('HR', 'Human Resource')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='request',
            name='status',
            field=models.IntegerField(blank=True, choices=[(1, 'Accepted'), (2, 'Rejected'), (0, 'Pending')], null=True),
        ),
        migrations.AlterField(
            model_name='revenue',
            name='stream',
            field=models.CharField(blank=True, choices=[('Government', 'Government'), ('Patient', 'Patient'), ('Donation', 'Donation')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='treatment',
            name='status',
            field=models.CharField(blank=True, choices=[('Canceled', 'Canceled'), ('Completed', 'Completed'), ('Pending', 'Pending')], max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='VitalSign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField(default=django.utils.timezone.now)),
                ('weight', models.IntegerField(blank=True, null=True)),
                ('diastolic', models.IntegerField(blank=True, null=True)),
                ('systolic', models.IntegerField(blank=True, null=True)),
                ('respiration', models.IntegerField(blank=True, null=True)),
                ('temperature', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vital_signs', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vital_sign_patient', to='management.patient')),
            ],
            options={
                'db_table': 'vital_sign',
                'ordering': ('-time',),
            },
        ),
        migrations.AddField(
            model_name='patient',
            name='vital_signs',
            field=models.ManyToManyField(blank=True, related_name='patient_vital_signs', to='management.VitalSign'),
        ),
    ]
