# Generated by Django 3.1.2 on 2020-11-09 12:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('management', '0020_auto_20201109_1224'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('medicine_type', models.CharField(blank=True, choices=[('Capsule', 'Capsule'), ('Syrup', 'Syrup'), ('Tablet', 'Tablet')], max_length=100, null=True)),
                ('boxes_bought', models.IntegerField(blank=True, null=True)),
                ('boxes_left', models.IntegerField(blank=True, null=True)),
                ('boxes_sold', models.IntegerField(blank=True, null=True)),
                ('pieces_per_boxes', models.IntegerField(blank=True, null=True)),
                ('pieces_sold', models.IntegerField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('manufacture_date', models.DateField(blank=True, null=True)),
                ('manufacturer', models.CharField(blank=True, max_length=200, null=True)),
                ('piece_selling_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medicines', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'medicine',
            },
        ),
        migrations.CreateModel(
            name='PrescribedMedicine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prescribed_medicines', to=settings.AUTH_USER_MODEL)),
                ('medicine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prescribed_medicine_medicine', to='pharmacy.medicine')),
            ],
            options={
                'db_table': 'prescibed_medicine',
            },
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prescription_id', models.CharField(blank=True, max_length=200, null=True)),
                ('dosage', models.CharField(blank=True, max_length=2000, null=True)),
                ('frequency', models.CharField(blank=True, max_length=200, null=True)),
                ('total', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('status', models.IntegerField(blank=True, choices=[(0, 'Not paid'), (1, 'Paid')], null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prescriptions', to=settings.AUTH_USER_MODEL)),
                ('medicines', models.ManyToManyField(blank=True, related_name='prescription_medicine', to='pharmacy.PrescribedMedicine')),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prescription_patient', to='management.patient')),
                ('treatment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prescription_treatment', to='management.treatment')),
            ],
            options={
                'db_table': 'prescription',
            },
        ),
        migrations.AddField(
            model_name='prescribedmedicine',
            name='prescription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prescribed_medicine_prescribed', to='pharmacy.prescription'),
        ),
        migrations.AddField(
            model_name='medicine',
            name='prescribed_medicines',
            field=models.ManyToManyField(blank=True, related_name='medicine_prescribed_medicines', to='pharmacy.PrescribedMedicine'),
        ),
    ]
