# Generated by Django 3.1.2 on 2020-11-10 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0005_auto_20201110_1155'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='total_cost_accumulated',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='medicine_type',
            field=models.CharField(blank=True, choices=[('Syrup', 'Syrup'), ('Tablet', 'Tablet'), ('Capsule', 'Capsule')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='status',
            field=models.IntegerField(blank=True, choices=[(0, 'Not paid'), (1, 'Paid')], null=True),
        ),
    ]
