# Generated by Django 3.1.2 on 2020-11-12 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0008_auto_20201111_1332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='medicine_type',
            field=models.CharField(blank=True, choices=[('Capsule', 'Capsule'), ('Tablet', 'Tablet'), ('Syrup', 'Syrup')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='status',
            field=models.IntegerField(blank=True, choices=[(1, 'Confirmed'), (0, 'Pending')], null=True),
        ),
    ]
