# Generated by Django 3.1.2 on 2020-11-12 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0010_auto_20201112_1455'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='is_paid',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
